select  s.SalesOrderID,
        s.OrderDate,
        s.DueDate,
        s.ShipDate,
        s.OnlineOrder,
        s.CustomerID,
        s.SalesPersonID,
        s.ProductID,
        t.Name as TerritoryName,
        s.ShipMethod,
        s.OriginalCurrency,
        s.DiscountType,
        s.Rate,
        s.UnitPrice,
        s.UnitPrice_USD,
        s.UnitPriceDiscount,
        s.OrderQty,
        s.GrossAmount,
        s.GrossAmount_USD,
        s.LineTotal,
        s.LineTotal_USD, 
        s.DiscountAmount,
        s.DiscountAmount_USD,
        s.TaxAmt,
        s.TaxAmt_USD,
        s.Freight,
        s.Freight_USD,
        s.OrderTotal,
        s.OrderTotal_USD     
from [staging].[sales] s  
left join Sales.SalesTerritory t on s.TerritoryID = t.TerritoryID